--
-- PostgreSQL database dump
--

-- Dumped from database version 14.6
-- Dumped by pg_dump version 14.6

-- Started on 2024-09-02 12:15:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 279 (class 1259 OID 61283)
-- Name: tab_mail_properties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tab_mail_properties (
    id bigint NOT NULL,
    active boolean NOT NULL,
    host character varying(255),
    password character varying(255),
    port integer NOT NULL,
    user_name character varying(255)
);


ALTER TABLE public.tab_mail_properties OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 61282)
-- Name: tab_mail_properties_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tab_mail_properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tab_mail_properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3500 (class 0 OID 61283)
-- Dependencies: 279
-- Data for Name: tab_mail_properties; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.tab_mail_properties (id, active, host, password, port, user_name) VALUES (1, true, 'smtp.slask.eu', 'SK@znik715450', 6355, 'wcpr-informacja');


--
-- TOC entry 3506 (class 0 OID 0)
-- Dependencies: 278
-- Name: tab_mail_properties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tab_mail_properties_id_seq', 1, false);


--
-- TOC entry 3353 (class 2606 OID 61289)
-- Name: tab_mail_properties tab_mail_properties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tab_mail_properties
    ADD CONSTRAINT tab_mail_properties_pkey PRIMARY KEY (id);


-- Completed on 2024-09-02 12:15:09

--
-- PostgreSQL database dump complete
--

